defaults: &defaults
  LL: 5
  TT: 2
  LT: 5
  TL: 5
  positive_masking_percent: &default_positive_masking [0, 25, 50, 75]
  random_state: &default_random_state 0

dpi_n:
  LL: 16
  TT: 4
  LT: 16
  TL: 16
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

te_pirna:
  LL: 16
  TT: 4
  LT: 16
  TL: 16
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

lncrna_cancer:
  LL: 9
  TT: 3
  LT: 9
  TL: 9
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

lncrna_disease:
  LL: 9
  TT: 3
  LT: 9
  TL: 9
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

lncrna_mirna:
  LL: 9
  TT: 3
  LT: 9
  TL: 9
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

dpi_g:
  LL: 9
  TT: 3
  LT: 9
  TL: 9
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

davis:
  LL: 9
  TT: 3
  LT: 9
  TL: 9
  positive_masking_percent: *default_positive_masking
  random_state: *default_random_state

mirna_disease: *defaults
dpi_i: *defaults
dpi_e: *defaults
srn: *defaults
ern: *defaults
kiba: *defaults
mirtarbase: *defaults
npinter: *defaults
