dpi_n:
  X: [datasets/dpi_n/X1.npy, datasets/dpi_n/X2.npy]
  y: datasets/dpi_n/y.npy
  pairwise: true

dpi_g:
  X: [datasets/dpi_g/X1.npy, datasets/dpi_g/X2.npy]
  y: datasets/dpi_g/y.npy
  pairwise: true

dpi_i:
  X: [datasets/dpi_i/X1.npy, datasets/dpi_i/X2.npy]
  y: datasets/dpi_i/y.npy
  pairwise: true

dpi_e:
  X: [datasets/dpi_e/X1.npy, datasets/dpi_e/X2.npy]
  y: datasets/dpi_e/y.npy
  pairwise: true

srn:
  X: [datasets/srn/X1.npy, datasets/srn/X2.npy]
  y: datasets/srn/y.npy
  pairwise: true

ern:
  X: [datasets/ern/X1.npy, datasets/ern/X2.npy]
  y: datasets/ern/y.npy
  pairwise: true

davis:
  X: [datasets/davis/X1.npy, datasets/davis/X2.npy]
  y: datasets/davis/y.npy
  pairwise: true

kiba:
  X: [datasets/kiba/X1.npy, datasets/kiba/X2.npy]
  y: datasets/kiba/y.npy
  pairwise: true

mirtarbase:
  X: [datasets/mirtarbase/X1.npy, datasets/mirtarbase/X2.npy]
  y: datasets/mirtarbase/y.npy
  pairwise: true

npinter:
  X: [datasets/npinter/X1.npy, datasets/npinter/X2.npy]
  y: datasets/npinter/y.npy
  pairwise: true
