bxt_gmo: estimators.simple_forests.bxt_gmo
full_bxt_bgso: estimators.simple_forests.bxt_bgso

dwnn_square_bxt_bgso: estimators.model_forest_definitions.dwnn_square_bxt_bgso
dwnn_softmax_bxt_bgso: estimators.model_forest_definitions.dwnn_softmax_bxt_bgso
dwnn_similarities_bxt_bgso: estimators.model_forest_definitions.dwnn_similarities_bxt_bgso
dwnn_max_bxt_bgso: estimators.model_forest_definitions.dwnn_max_bxt_bgso
dwnn_conditional_uniform_bxt_bgso: estimators.model_forest_definitions.dwnn_conditional_uniform_bxt_bgso
uniform_bxt_bgso: estimators.model_forest_definitions.uniform_bxt_bgso