small_bxt_gmo: estimators.bipartite_forests.small_bxt_gmo
bxt_gmo: estimators.bipartite_forests.bxt_gmo
bxt_bgso: estimators.bipartite_forests.bxt_bgso

dwnn_square_bxt_bgso: estimators.model_forests.estimators.dwnn_square_bxt_bgso
dwnn_softmax_bxt_bgso: estimators.model_forests.estimators.dwnn_softmax_bxt_bgso
dwnn_similarities_bxt_bgso: estimators.model_forests.estimators.dwnn_similarities_bxt_bgso
dwnn_max_bxt_bgso: estimators.model_forests.estimators.dwnn_max_bxt_bgso
dwnn_conditional_uniform_bxt_bgso: estimators.model_forests.estimators.dwnn_conditional_uniform_bxt_bgso
uniform_bxt_bgso: estimators.model_forests.estimators.uniform_bxt_bgso

mlp: estimators.literature_models.estimators.mlp
kron_rls: estimators.literature_models.estimators.kron_rls
lmo_rls: estimators.literature_models.estimators.lmo_rls
dthybrid: estimators.literature_models.estimators.dthybrid_regressor
blmnii_rls: estimators.literature_models.estimators.blmnii_rls
blmnii_svm: estimators.literature_models.estimators.blmnii_svm
nrlmf: estimators.literature_models.nrlmf.nrlmf_regressor

ss_mse_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__mse_fixed
ss_md_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_fixed
ss_ad_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__ad_fixed
# ss_ad_mse_bxt_bgso: estimators.semisupervised_forests.ss_bgso__ad_mse_fixed
# ss_ad_md_bxt_bgso: estimators.semisupervised_forests.ss_bgso__ad_md_fixed

ss_md_fixed_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_fixed
ss_md_random_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_random
ss_md_size_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_size
ss_md_inverse_size_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_inverse_size

ss_md_density_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_density
ss_md_inverse_density_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_inverse_density

dwnn_similarities_ss_md_size_bxt_bgso: estimators.semisupervised_forests.ss_model_forests.dwnn_similarities__ss_md_size__bxt_bgso
dwnn_square_ss_md_size_bxt_bgso: estimators.semisupervised_forests.ss_model_forests.dwnn_square__ss_md_size__bxt_bgso
nrlmf_dwnn_square_ss_md_size_bxt_bgso: estimators.semisupervised_forests.ss_model_forests.nrlmf__dwnn_square__ss_md_size__bxt_bgso

nrlmf_bxt_bgso: estimators.forests_with_nrlmf.nrlmf__bxt_bgso
nrlmf_bxt_gmo: estimators.forests_with_nrlmf.nrlmf__bxt_gmo
nrlmf_dwnn_similarities_bxt_bgso: estimators.forests_with_nrlmf.nrlmf__dwnn_similarities__bxt_bgso
nrlmf_dwnn_square_bxt_bgso: estimators.forests_with_nrlmf.nrlmf__dwnn_square__bxt_bgso