small_bxt_gmo: estimators.simple_forest_definitions.small_bxt_gmo
bxt_gmo: estimators.simple_forest_definitions.bxt_gmo
bxt_bgso: estimators.simple_forest_definitions.bxt_bgso

dwnn_square_bxt_bgso: estimators.model_forest_definitions.dwnn_square_bxt_bgso
dwnn_softmax_bxt_bgso: estimators.model_forest_definitions.dwnn_softmax_bxt_bgso
dwnn_similarities_bxt_bgso: estimators.model_forest_definitions.dwnn_similarities_bxt_bgso
dwnn_max_bxt_bgso: estimators.model_forest_definitions.dwnn_max_bxt_bgso
dwnn_conditional_uniform_bxt_bgso: estimators.model_forest_definitions.dwnn_conditional_uniform_bxt_bgso
uniform_bxt_bgso: estimators.model_forest_definitions.uniform_bxt_bgso

mlp: estimators.literature_models.estimators.mlp
kron_rls: estimators.literature_models.estimators.kron_rls
lmo_rls: estimators.literature_models.estimators.lmo_rls
dthybrid: estimators.literature_models.estimators.dthybrid_regressor
blmnii_rls: estimators.literature_models.estimators.blmnii_rls
blmnii_svm: estimators.literature_models.estimators.blmnii_svm

ss_mse_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__mse_fixed
ss_md_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_fixed
ss_ad_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__ad_fixed
# ss_ad_mse_bxt_bgso: estimators.semisupervised_forests.ss_bgso__ad_mse_fixed
# ss_ad_md_bxt_bgso: estimators.semisupervised_forests.ss_bgso__ad_md_fixed

ss_md_fixed_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_fixed
ss_md_random_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_random
ss_md_size_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_size
ss_md_inverse_size_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_inverse_size

ss_md_density_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_density
ss_md_inverse_density_bxt_bgso: estimators.semisupervised_forests.estimators.ss_bxt_gso__md_inverse_density
