- out: results/dwnn_weights
  estimator:
  - bxt_bgso
  - dwnn_square_bxt_bgso
  - dwnn_softmax_bxt_bgso
  - dwnn_similarities_bxt_bgso
  - dwnn_max_bxt_bgso
  - dwnn_conditional_uniform_bxt_bgso
  - uniform_bxt_bgso
  scoring: &default_scoring
  - TT__auroc
  - LT__auroc
  - TL__auroc
  - TT__auprc
  - LT__auprc
  - TL__auprc
  validation_setting:
  - TT
  # - TT_50
  dataset: &all_datasets
  - dpi_n
  - dpi_g
  - davis
  - dpi_i
  - dpi_e
  - srn
  - ern
  - kiba
  - npinter
  - mirtarbase
  scoring: *default_scoring
  validation_setting:
  - TT
  dataset: *all_datasets


- out: results/dynamic_supervision
  estimator:
  - ss_md_fixed_bxt_bgso
  - ss_md_random_bxt_bgso
  - ss_md_size_bxt_bgso
  - ss_md_inverse_size_bxt_bgso
  - ss_md_density_bxt_bgso
  - ss_md_inverse_density_bxt_bgso

- out: results/unsupervised_impurities
  estimator:
  - bxt_bgso
  - ss_mse_bxt_bgso
  - ss_md_bxt_bgso
  - ss_ad_bxt_bgso
  scoring: *default_scoring
  validation_setting:
  - TT
  dataset: *all_datasets
