- out: results/unsupervised_impurities
  estimator:
  - ss_mse_bxt_bgso
  - ss_md_bxt_bgso
  - ss_ad_mse_bxt_bgso
  - ss_ad_md_bxt_bgso
  scoring: [auroc, auprc]
  validation_setting: [LL, TT, LT, TL, TT_50]
  dataset:  &all_datasets
  - dpi_n
  - dpi_g
  - davis
  - dpi_i
  - dpi_e
  - srn
  - ern
  - kiba
  - npinter
  - mirtarbase