- out: results/literature_methods
  estimator:
  - nrlmf_dwnn_square_bxt_bgso
  # - nrlmf_dwnn_similarities_bxt_bgso
  # - dwnn_similarities_bxt_bgso
  - ss_md_bxt_bgso
  - bxt_bgso
  - nrlmf_bxt_gmo
  - nrlmf_bxt_bgso
  - nrlmf
  - kron_rls
  - blmnii_rls
  - blmnii_svm
  - lmo_rls
  - dthybrid
  - mlp
  scoring: &default_scoring
  - TT__auroc
  - LT__auroc
  - TL__auroc
  # - LL_M__auroc

  - TT__auprc
  - LT__auprc
  - TL__auprc
  # - LL_M__auprc
  validation_setting: &default_validation_setting
  - TT
  - TT_50
  - TT_25
  - TT_75
  dataset: &all_datasets
  - dpi_n
  - dpi_g
  - davis
  - dpi_i
  - dpi_e
  - srn
  - ern
  - kiba
  - npinter
  - mirtarbase
  active: true

- out: results/y_reconstruction
  estimator:
  - bxt_bgso
  - nrlmf_bxt_bgso
  - dwnn_square_bxt_bgso
  - nrlmf_dwnn_square_bxt_bgso
  - dwnn_square_ss_md_size_bxt_bgso
  - nrlmf_dwnn_square_ss_md_size_bxt_bgso
  scoring: *default_scoring
  validation_setting: *default_validation_setting
  dataset: *all_datasets
  active: true

- out: results/dwnn_weights
  estimator:
  - bxt_bgso
  - dwnn_square_bxt_bgso
  - dwnn_softmax_bxt_bgso
  - dwnn_similarities_bxt_bgso
  - dwnn_max_bxt_bgso
  - dwnn_conditional_uniform_bxt_bgso
  - uniform_bxt_bgso
  scoring: *default_scoring
  validation_setting: *default_validation_setting
  dataset: *all_datasets
  active: true

- out: results/dynamic_supervision
  estimator:
  - ss_md_fixed_bxt_bgso
  - ss_md_random_bxt_bgso
  - ss_md_size_bxt_bgso
  - ss_md_inverse_size_bxt_bgso
  - ss_md_density_bxt_bgso
  - ss_md_inverse_density_bxt_bgso
  scoring: *default_scoring
  validation_setting: *default_validation_setting
  dataset: *all_datasets
  active: false  # FIXME

- out: results/unsupervised_impurities
  estimator:
  - bxt_bgso
  - ss_mse_bxt_bgso
  - ss_md_bxt_bgso
  - ss_ad_bxt_bgso
  scoring: *default_scoring
  validation_setting: *default_validation_setting
  dataset: *all_datasets
  active: false  # FIXME
