estimator:
  nrlmf_bxt_gmo: BICTR[Deep]
  # nrlmf_bxt_bgso: NRLMF + BGSO
  nrlmf_bxt_bgso: NRLMF + Oxytrees[Deep]
  bxt_bgso_logistic: Oxytrees[Logistic]

  bxt_bgso_kronrls: Oxytrees[RLS-Kron]
  nrlmf_bxt_bgso_kronrls: NRLMF + Oxytrees[RLS-Kron]

  dwnn_similarities_bxt_bgso: Oxytrees[SWN]
  nrlmf_dwnn_similarities_bxt_bgso: NRLMF + Oxytrees[SWN]

  # uniform_bxt_bgso: GMO\textsubscript{SA}
  # nrlmf_uniform_bxt_bgso: NRLMF + GMO\textsubscript{SA}
  uniform_bxt_bgso: Oxytrees[Mean]
  nrlmf_uniform_bxt_bgso: NRLMF + Oxytrees[Mean]

  dwnn_conditional_uniform_bxt_bgso: GMO

  nrlmf: NRLMF
  dwnn: SWN
  mlp: MLP
  logistic: LR
  kron_rls: RLS-Kron
  blmnii_rls: BLMNII[RLS]
  lmo_rls: LMO[RLS]
  dthybrid: DTHybrid


dataset:
  dpi_n: DPI-N
  dpi_g: DPI-G
  davis: Davis
  dpi_i: DPI-I
  dpi_e: DPI-E
  srn: SRN
  ern: ERN
  kiba: KIBA
  npinter: NPInter
  mirtarbase: miRTarBase
  te_pirna: TE-Pirna
  lncrna_cancer: LncRNA-Cancer
  lncrna_disease: LncRNA-Disease
  lncrna_mirna: LncRNA-MiRNA
  mirna_disease: MiRNA-Disease


metric:
  TT__auroc: AUROC (Inductive)
  TT__auprc: AUPRC (Inductive)
  LT__auroc: AUROC (LT)
  LT__auprc: AUPRC (LT)
  TL__auroc: AUROC (TL)
  TL__auprc: AUPRC (TL)
  LT+TL__auroc: AUROC (Semi-inductive)
  LT+TL__auprc: AUPRC (Semi-inductive)
  LL_M__auroc: AUROC (Transductive)
  LL_M__auprc: AUPRC (Transductive)
