test_all_datasets:
  active: true
  description: Test the validation configuration of all datsets.
  estimator: [small_bxt_gmo]
  dataset:
  - dpi_n
  - dpi_g
  - davis
  - dpi_i
  - dpi_e
  - srn
  - ern
  - kiba
  - npinter
  - mirtarbase
  scoring: [auroc, auprc]
  validation_setting:
  # Most important settings first
  - TT
  - TT_50
  - TT_25
  - TT_75

  - LT
  - TL
  - LL

  - LT_25
  - LT_50
  - LT_75

  - TL_25
  - TL_50
  - TL_75

